"""Initial migration

Revision ID: 64878ba1b23a
Revises: 
Create Date: 2025-05-14 14:35:53.064805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64878ba1b23a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('comp_link', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('bracket', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_competitions_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('league', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('twitch', sa.String(length=255), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_players_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_competitions',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('competition_id', 'shared_with_user_id')
    )
    op.create_table('shared_players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'shared_with_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_players')
    op.drop_table('shared_competitions')
    op.drop_table('players')
    op.drop_table('competitions')
    op.drop_table('users')
    # ### end Alembic commands ###
