"""Initial migration

Revision ID: b030628355a2
Revises: 
Create Date: 2025-05-10 16:34:04.673376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b030628355a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('result_url', sa.String(length=255), nullable=True),
    sa.Column('detail_url', sa.String(length=255), nullable=True),
    sa.Column('comp_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('event_line1', sa.String(length=255), nullable=True),
    sa.Column('event_line2', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('players')
    op.drop_table('competitions')
    # ### end Alembic commands ###
